apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-test
  region: eu-central-1

vpc: # если не указывать, создаст свою сеть
  subnets:
    public:
      eu-central-1a: { id: subnet-057d7db30bc58a0ef }
      eu-central-1b: { id: subnet-038905b5d3f7c0d09 }  
      eu-central-1c: { id: subnet-074f1e6c26f0f416b }


nodeGroups:
  - name           : worker-nodes-group-1
    instanceType   : t2.medium
    labels: { role: workers }
    desiredCapacity: 1
    ssh: # use existing EC2 key
      publicKeyName: 	Frankfurt-vish
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true
